set nocompatible
source ~/.config/vi/exrc

set viminfo+=n$XDG_CACHE_HOME/vi/viminfo
if has('syntax') && !exists('g:syntax_on')
  syntax enable
endif

set softtabstop=4
set smartindent
set guicursor=
set nowrap
set nohlsearch
set noswapfile
set nobackup
set undodir=$XDG_CACHE_HOME/vim/undodir
set undofile
set scrolloff=3
set colorcolumn=129
set cursorline
highlight CursorLine cterm=NONE ctermbg=255

