" classic vi loads config from exrc, so we need to start with it
source $XDG_CONFIG_HOME/vi/exrc

" load vim defaults
unlet! g:skip_defaults_vim
source $VIMRUNTIME/defaults.vim

" undo & recovery bits
set noswapfile
set nobackup
set viminfo+=n$XDG_STATE_HOME/vi/viminfo
if !empty($XDG_STATE_HOME) && !isdirectory($XDG_STATE_HOME . '/vi/undodir')
  call mkdir($XDG_STATE_HOME . '/vi/undodir', 'p', 0700)
endif " this creates the undodir if it doesnt already exist, would silently fail otherwise 
set undodir=$XDG_STATE_HOME/vi/undodir
set undofile

" editing
set softtabstop=4
set textwidth=128
set ignorecase smartcase
set hidden

" display
set mouse=
set guicursor=
set nowrap
set nohlsearch
set scrolloff=3
set colorcolumn=+1
set cursorline
set belloff=all

augroup MyColorsset 
  autocmd!
  autocmd ColorScheme * highlight CursorLine cterm=NONE ctermbg=255
augroup END
doautocmd ColorScheme

set background=light
colorscheme lunaperche

